export type Post = {
  slug: string;
  title: string;
  date: string; // ISO or yyyy/mm/dd
  excerpt: string;
  description?: string;
  keywords?: string[];
  content: string; // plain text with optional single-line image URLs
};

export const posts: Post[] = [
  {
    slug: 'how-to-scan-qr-codes-online',
    title: 'How to Scan QR Codes Online (Mobile & Desktop)',
    date: '2025/9/7',
    excerpt: 'Fast ways to scan QR codes with your phone camera or by uploading an image—no app needed.',
    description:
      'Learn how to scan QR codes online using a live camera or an uploaded image, plus real-life use cases, FAQs, and pro tips.',
    keywords: [
      'online qr code scanner',
      'scan qr code with camera',
      'scan qr code from image',
      'wifi qr code',
      'qr code login',
      'qr code ingredients'
    ],
    content: [
      'Why Use an Online QR Code Scanner? 🤔',
      '',
      'Most people run into the same problems when scanning QR codes:',
      '',
      '-Installing apps is annoying:** Every new scanner app takes storage, shows ads, or asks for permissions.',
      '-Typing long URLs is painful:** Some QR codes just redirect to websites—typing them manually is slow.',
      '-Privacy concerns:** Not everyone wants third-party apps accessing their camera or contacts.',
      '',
      '👉An online scanner solves these pain points:** No downloads, no ads, works instantly in your browser, and keeps your data private.',
      '',
      '---',
      '',
      'Real-Life Use Cases',
      '',
      '1. Connect to Wi‑Fi in One Click 📶',
      '',
      "At a café or airport and don’t want to type a long Wi‑Fi password?",
      '',
      'Open [Camera Scan](/scan#camera), point at the Wi‑Fi QR code, and get online immediately.',
      '',
      'Keywords: scan Wi‑Fi QR code, connect without typing, free Wi‑Fi QR login.',
      '',
      '---',
      '',
      '2. Check Product Details 🥫',
      '',
      'Looking at food packaging and curious about ingredients or production dates?',
      '',
      'Use [Upload Scan](/scan#upload) to take or upload a picture of the QR code—see the details instantly.',
      '',
      'Keywords: QR code ingredients, product QR check, verify product QR code.',
      '',
      '---',
      '',
      '3. Log In to Big‑Screen Devices 🖥️',
      '',
      'Need to log in on a TV or computer but hate typing passwords?',
      '',
      'Open [Camera Scan](/scan#camera), scan the QR code shown on the screen, and you’re in.',
      '',
      'Keywords: QR login, TV QR code, device pairing QR._',
      '',
      '---',
      '',
      'How to Use This Tool',
      '',
      '1. Click [Camera Scan](/scan#camera), grant camera access, and scan live.',
      '2. Or click [Upload Scan](/scan#upload), choose a QR code image from your gallery.',
      '3. The result will appear instantly—tap the link to open it.',
      '',
      '---',
      '',
      'Frequently Asked Questions (FAQ) ❓',
      '',
      'Q1: Is online scanning safe?',
      '',
      'A:Yes. All decoding happens locally in your browser. No images are uploaded to any server.',
      '',
      'Q2: What types of QR codes are supported?',
      '',
      'A:We support common types like URLs, Wi‑Fi, payment codes, and plain text.',
      '',
      'Q3: Why can’t my camera recognize the code?',
      '',
      'A:Make sure the QR code is well lit, not tilted, and in focus. If it still fails, try [Upload Scan](/scan#upload).',
      '',
      'Q4: Does it work on both iPhone and Android?',
      '',
      'A:Yes. It works in any modern mobile browser.',
      '',
      'Q5: Is it free?',
      '',
      'A:100% free to use, no ads.',
      '',
      '---',
      '',
      'Pro Tips for Better Recognition 💡',
      '',
      '- Use good lighting and avoid blur.',
      '- Keep the whole QR code visible in the frame.',
      '- If the camera struggles, upload an image instead.',
      '- Straighten the QR code so the edges are sharp.',
      '',
      '---',
      '',
      'Conclusion',
      '',
      'An online QR code scanner means:',
      '',
      '- No installs',
      '- No storage waste',
      '- Better privacy',
      '- Instant results',
      '',
      'Try it now:** [Camera Scan](/scan#camera) or [Upload Scan](/scan#upload)! 🚀',
      '',
      '![Scan QR Codes Online](https://via.placeholder.com/1200x630.png?text=Scan+QR+Codes+Online)'
    ].join('\n')
  }
];