export type Post = {
  slug: string;
  title: string;
  date: string; // ISO or yyyy/mm/dd
  excerpt: string;
  description?: string;
  keywords?: string[];
  content: string; // plain text with optional single-line image URLs
};

export const posts: Post[] = [
  {
    slug: 'how-to-scan-qr-codes-online',
    title: 'Scan QR Codes Online — Quick Guide',
    date: '2025/9/7',
    excerpt: 'Fast ways to scan QR codes with your camera or by uploading an image — private, instant, no app needed.',
    description:
      'Learn how to scan QR codes online using your camera or an uploaded image. Step-by-step guide with real use cases, FAQs, and privacy tips.',
    keywords: [
      'online qr code scanner',
      'scan qr code with camera',
      'scan qr code from image',
      'wifi qr code',
      'qr code login',
      'qr code ingredients'
    ],
    content: [
      '## Overview',
      '',
      'Most people run into the same problems when scanning QR codes:',
      '',
      '- Installing apps is annoying: every new scanner app takes storage, shows ads, or asks for permissions.',
      '- Typing long URLs is painful: some QR codes just redirect to websites - typing them manually is slow.',
      '- Privacy concerns: you may not want third-party apps accessing your camera or contacts.',
      '',
      'An online scanner solves these pain points: no downloads, no ads, works instantly in your browser, and keeps your data private.',
      '',
      '---',
      '',
      '## Real-Life Use Cases',
      '',
      '### Connect to Wi-Fi quickly',
      '',
      'Open Camera Scan',
      'Then point at the Wi-Fi QR code and connect without typing.',
      '',
      'Keywords: scan Wi-Fi QR code, connect without typing, free Wi-Fi QR login.',
      '',
      '---',
      '',
      '### Check Product Details',
      '',
      'Use Upload Scan to take or upload a picture of the QR code:',
      'You will see the details instantly.',
      '',
      'Keywords: QR code ingredients, product QR check, verify product QR code.',
      '',
      '---',
      '',
      '### Log In to Big-Screen Devices',
      '',
      'Open Camera Scan',
      'Scan the QR code shown on the TV or computer to log in quickly.',
      '',
      'Keywords: QR login, TV QR code, device pairing QR.',
      '',
      '---',
      '',
      '## How to Use This Tool',
      '',
      '1. Click Camera Scan and grant camera access:',
      '2. Or click Upload Scan and choose a QR code image:',
      '3. The result will appear instantly. Click to open the link or copy the text.',
      '',
      '---',
      '',
      '## Frequently Asked Questions (FAQ)',
      '',
      'Q1: Is online scanning safe?',
      'A: Yes. All decoding happens locally in your browser. No images are uploaded to any server.',
      '',
      'Q2: What types of QR codes are supported?',
      'A: We support common types like URLs, Wi-Fi, payment codes, and plain text.',
      '',
      'Q3: Why can\'t my camera recognize the code?',
      'A: Make sure the QR code is well lit, not tilted, and in focus. If it still fails, try Upload Scan:',
      '',
      'Q4: Does it work on both iPhone and Android?',
      'A: Yes. It works in any modern mobile browser.',
      '',
      'Q5: Is it free?',
      'A: 100% free to use, no ads.',
      '',
      '---',
      '',
      '## Pro Tips for Better Recognition',
      '',
      '- Use good lighting and avoid blur.',
      '- Keep the whole QR code visible in the frame.',
      '- If the camera struggles, upload an image instead.',
      '- Straighten the QR code so the edges are sharp.',
      '',
      '---',
      '',
      '## Conclusion',
      '',
      'An online QR code scanner means:',
      '- No installs',
      '- No storage waste',
      '- Better privacy',
      '- Instant results',
      '',
      'Try it now:',
      'Go to Scan Page',
      '',
      '---',
      '## Try Our Free QR Scanner Tools',
      '',
      'Want to put these tips into practice?  ',
      '- Use our Camera QR Scanner to scan instantly with your webcam.  ',
      '- Try the Upload QR Code Tool to decode images and screenshots.  ',
      '- Or visit the Main Scan Page for all features in one place.  ',
      '',
      'Fast, private, and 100% free — start scanning QR codes now.',
      '',
      '/og-default.png'
    ].join('\n')
  },
  {
    slug: 'scan-qr-code-on-pc-mac-without-app',
    title: 'Scan QR Code on PC or Mac Without App',
    date: '2025/9/26',
    excerpt: 'Learn how to scan QR codes on PC or Mac without apps. Use a free online QR scanner to decode screenshots or images instantly, privately, and securely.',
    description:
      'Scan QR codes on PC or Mac without apps. Upload images or use your webcam with a free online QR scanner — private, fast, and secure.',
    keywords: [
      'scan qr code on pc',
      'scan qr code on mac',
      'qr code scanner online',
      'scan qr from screenshot',
      'scan qr without app'
    ],
    content: [
      '## Introduction',
      '',
      'Many people think scanning QR codes is only possible with a phone. But what if you are on a PC or Mac and receive a QR code inside an email, a screenshot, or a slide deck? Installing third-party apps is unnecessary. You can scan QR codes directly online without downloads.',
      '',
      '---',
      '',
      '### Method 1 — Upload an Image or Screenshot',
      '',
      '1. Go to Upload Scan',
      '2. Drag and drop your screenshot or image file into the upload box.',
      '3. The QR code will be decoded instantly in your browser.',
      '',
      'Tips:',
      '- Works with PNG, JPG, and WebP.',
      '- You can also copy and paste a screenshot from your clipboard.',
      '',
      '---',
      '',
      '### Method 2 — Use Your Webcam in the Browser',
      '',
      '1. Open Camera Scan',
      '2. Grant access to your webcam.',
      '3. Hold the QR code in front of the camera and wait for the result.',
      '',
      'This makes your computer behave like a built-in QR code scanner without any extra apps.',
      '',
      '---',
      '',
      '### Method 3 — Built-in System Options',
      '',
      '- On macOS, Preview or Photos app can sometimes detect QR codes in images, but not always reliable.',
      '- On Windows, the default Camera app does not decode QR codes by itself. Using an online tool is faster and more consistent.',
      '',
      '---',
      '',
      '## Privacy and Security',
      '',
      'All decoding happens locally in your browser. Images are not uploaded to any server. This ensures your data remains private.',
      '',
      '---',
      '',
      '## Common Questions',
      '',
      'Q1: Do I need to install software?',
      'A: No. Both methods work directly in the browser.',
      '',
      'Q2: Does it work offline?',
      'A: You need internet to load the page, but decoding runs in-browser.',
      '',
      'Q3: Is it free?',
      'A: Yes. The tool is free to use with no ads.',
      '',
      '---',
      '',
      '## Conclusion',
      '',
      'Scanning a QR code on PC or Mac without an app is simple:',
      '- Upload an image or screenshot',
      '- Use your webcam directly in the browser',
      '- Enjoy instant, private, free results',
      '',
      'Try it now:',
      'Go to Scan Page',
      '',
      '---',
      '## Try Our Free QR Scanner Tools',
      '',
      'Want to put these tips into practice?  ',
      '- Use our Camera QR Scanner to scan instantly with your webcam.  ',
      '- Try the Upload QR Code Tool to decode images and screenshots.  ',
      '- Or visit the Main Scan Page for all features in one place.  ',
      '',
      'Fast, private, and 100% free — start scanning QR codes now.',
      '',
      '/og-default.png'
    ].join('\n')
  },
  {
    slug: 'free-online-qr-code-reader',
    title: 'Free Online QR Code Reader',
    date: '2025/9/26',
    excerpt: 'Use a free online QR code reader in your browser. Decode QR codes from photos, screenshots, or your webcam — private, secure, no app required.',
    description:
      'Free online QR code reader in your browser. Decode QR codes from photos, screenshots, or webcam — private, secure, and no app required.',
    keywords: [
      'free qr code reader',
      'online qr code reader',
      'scan qr from photo',
      'scan qr from screenshot',
      'qr scanner no app'
    ],
    content: [
      '## Introduction',
      '',
      'Looking for a free QR code reader without the hassle of apps? You can scan and decode QR codes directly in your browser. Whether you have a photo, a screenshot, or a printed code, this online tool makes it simple and private.',
      '',
      '---',
      '',
      '### Method 1 — Decode From a Photo or Screenshot',
      '',
      '1. Visit Upload Scan',
      '2. Upload your image or drag and drop a screenshot.',
      '3. Get instant results with no installation required.',
      '',
      'This method works on PC, Mac, and mobile browsers alike.',
      '',
      '---',
      '',
      '### Method 2 — Scan With Your Webcam',
      '',
      '1. Open Camera Scan',
      '2. Allow camera access in your browser.',
      '3. Hold the QR code up to the webcam and decode instantly.',
      '',
      'Perfect for scanning codes on paper, packaging, or another screen.',
      '',
      '---',
      '',
      '## Why Choose an Online Reader Over Apps?',
      '',
      '- No downloads or updates required',
      '- 100% free and ad-free',
      '- Works on all devices with a modern browser',
      '- Privacy first: decoding runs locally in your browser',
      '',
      '---',
      '',
      '## Frequently Asked Questions',
      '',
      'Q1: Is this free QR code reader really free?',
      'A: Yes. It is completely free to use, with no hidden costs.',
      '',
      'Q2: Does it work on mobile as well as desktop?',
      'A: Absolutely. Any modern browser on Android, iOS, Windows, or macOS is supported.',
      '',
      'Q3: What image formats are supported?',
      'A: Common formats such as PNG, JPG, and WebP.',
      '',
      'Q4: Can it scan barcodes too?',
      'A: Currently optimized for QR codes. Barcode support may come later.',
      '',
      '---',
      '',
      '## Conclusion',
      '',
      'A free online QR code reader is the easiest way to decode codes without extra software. Upload an image or use your camera, and get fast, private results.',
      '',
      'Try it now:',
      'Go to Scan Page',
      '',
      '---',
      '## Try Our Free QR Scanner Tools',
      '',
      'Want to put these tips into practice?  ',
      '- Use our Camera QR Scanner to scan instantly with your webcam.  ',
      '- Try the Upload QR Code Tool to decode images and screenshots.  ',
      '- Or visit the Main Scan Page for all features in one place.  ',
      '',
      'Fast, private, and 100% free — start scanning QR codes now.',
      '',
      '/og-default.png'
    ].join('\n')
  }
];